---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# This is a placeholder for the actual Argo CD manifests
# We'll use a kustomize base to include all necessary resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
